---
- name: set the /boot/firmware/cmdline.txt properly
  copy:
    content: 'net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc\n'
    dest: /boot/firmware/cmdline.txt
  notify:
    - reboot
