kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-v3
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-client-v3"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
