---
- name: upgrade all packages
  become: yes
  apt:
    update_cache: yes
    upgrade: full
    autoremove: yes
    # cache is valid for 3 hours
    cache_valid_time: 10800

- name: install microk8s snap
  become: yes
  community.general.snap:
    name: microk8s
    classic: yes
    channel: "{{ prereqs_microk8s_snap_channel }}"
    state: present

- name: set up ubuntu user to microk8s group
  become: yes
  user:
    name: ubuntu
    groups: microk8s
  notify:
    - reboot

- name: make sure ubuntu own /home/ubuntu/.kube
  become: yes
  file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    recurse: yes

- name: print hostname
  tags: verify
  ansible.builtin.debug:
    msg: System {{ inventory_hostname }} has assigned_hostname {{ assigned_hostname }}
    verbosity: 1

- name: set hostname
  become: yes
  ansible.builtin.hostname:
    name: "{{ assigned_hostname }}"

- ansible.builtin.set_fact:
    prereqs_output_filename: "{{ prereqs_ssh_config_output_dir }}/pik8s-{{ stage }}.config"
  tags:
    - outputs

- name: output ssh config file
  tags:
    - outputs
  local_action: ansible.builtin.template src=pi-k8s-config.j2 dest="{{ prereqs_output_filename }}"
  run_once: True

- name: note to user
  tags:
    - outputs
  ansible.builtin.debug:
    msg: "An ssh config for this {{ stage }} cluster has been output to {{ prereqs_output_filename }}"
