# etcdOperator
etcdOperator:
  image:
    repository: etcd_operator
    tag: 0.9.4_arm64
    pullPolicy: IfNotPresent

# backup spec
backupOperator:
  image:
    repository: etcd_operator
    tag: 0.9.4_arm64
    pullPolicy: IfNotPresent

# restore spec
restoreOperator:
  image:
    repository: etcd_operator
    tag: 0.9.4_arm64
    pullPolicy: IfNotPresent

## etcd-cluster specific values
etcdCluster:
  image:
    repository: quay.io/coreos/etcd
    tag: v3.2.25
    pullPolicy: Always
