apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: "etcd"
  namespace: "etcd"
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  # annotations:
  #   etcd.database.coreos.com/scope: clusterwide
spec:
  size: 3
  version: v3.4.9
  image:
    repository: etcd
    tag: v3.4.9
    pullPolicy: Never
  env:
  - name: ETCD_UNSUPPORTED_ARCH
    value: "arm64"
