apiVersion: v1
kind: Service
metadata:
  name: coredns-service
  namespace: dns
spec:
  selector:
    app.kubernetes.io/instance: ext-coredns
  ports:
    - port: 53
      targetPort: 53
      protocol: UDP
  type: LoadBalancer
