---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  name: nginx
  namespace: default

spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1
        name: nginx
        ports:
        - containerPort: 80
          name: http

---
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: test-dns.example.org
  name: nginx
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer

